#!/bin/bash

set -e

if [[ ! $# -eq 1 ]]; then
    echo "too few/many args"
    exit
fi


#partitions
parted --script -a optimal $1 \
    mklabel gpt \
    mkpart primary fat32 1MiB 300MiB \
    mkpart primary ext4 300MiB 100% \
    set 1 esp on

mkfs.fat -F32 "${1}1"
mkfs.ext4 -F "${1}2"
mount "${1}2" /mnt
mkdir /mnt/home
mkdir /mnt/etc
genfstab -U -p /mnt >> /mnt/etc/fstab

pacstrap /mnt base
arch-chroot /mnt

