#!/bin/bash

set -e

if [[ $# -eq 2 ]]; then
    archinstalldrive="${1}"
    archinstalluser="${2}"
else
    echo "Sorry for the prompts. Command line options to eliminate those coming soon! (but secretly I have included some for the dev, which is me, so get rekt)"
fi

if [[ -z "$archinstalldrive" ]]; then
    read -p "What drive are we installing to? (i.e. /dev/sdx): " archinstalldrive
fi

if [[ -z "$archinstalluser" ]]; then
    read -p "Choose your username: " archinstalluser
fi

parted --script -a optimal $archinstalldrive \
    mklabel gpt \
    mkpart primary fat32 1MiB 300MiB \
    mkpart primary ext4 300MiB 100% \
    set 1 esp on

mkfs.fat -F32 "${archinstalldrive}1"
mkfs.ext4 -F "${archinstalldrive}2"
mount "${archinstalldrive}2" /mnt
mkdir /mnt/home
mkdir /mnt/etc
genfstab -U -p /mnt >> /mnt/etc/fstab

pacstrap /mnt base

cat <<EOF > /mnt/root/install-part2
#!/bin/bash

set -e

pacman -S linux linux-headers linux-lts linux-lts-headers base-devel openssh networkmanager wpa_supplicant wireless_tools netctl dialog lvm2 --noconfirm
systemctl enable NetworkManager

sed -i 's/block filesystems/block lvm2 filesystems/g' /etc/mkinitcpio.conf

mkinitcpio -p linux
mkinitcpio -p linux-lts


sed -i 's/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g' /etc/locale.gen

locale-gen

useradd -m -g users -G wheel $archinstalluser
passwd $archinstalluser

which sudo > /dev/null 2>&1
if [[ \$? != 0 ]]; then
    pacman -S sudo --noconfirm
fi

sed -i 's/# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/g' /etc/sudoers

pacman -S grub efibootmgr dosfstools os-prober mtools --noconfirm

mkdir /boot/EFI
mount "${archinstalldrive}1" /boot/EFI
grub-install --target=x86_64-efi --bootloader-id=grub_uefi --recheck

if [[ ! -d /boot/grub/locale ]]; then
    mkdir /boot/grub/locale
fi

cp /usr/share/locale/en\@quot/LC_MESSAGES/grub.mo /boot/grub/locale/en.mo

grub-mkconfig -o /boot/grub/grub.cfg
EOF

chmod +x /mnt/root/install-part2
arch-chroot /mnt /root/install-part2
rm /mnt/root/install-part2

umount -a

reboot