#!/bin/bash

set -e

if [[ ! $# -eq 1 ]]; then
    echo "too few/many args"
    exit
fi

pacman -S grub efibootmgr dosfstools os-prober mtools --noconfirm

mkdir /boot/EFI
mount "${1}" /boot/EFI
grub-install --target=x86_64-efi --bootloader -id=grub_uefi --recheck

if [[ ! -d /boot/grub/locale ]]; then
    mkdir /boot/grub/locale
fi

cp /usr/share/locale/en\@quot/LC_MESSAGES/grub.mo /boot/grub/locale/en.mo

grub-mkconfig -o /boot/grub/grub.cfg

echo "Exit now, then do 'umount -a' and reboot."

