#!/bin/bash

set -e

pacman -S linux linux-headers linux-lts linux-lts-headers base-devel openssh networkmanager wpa_supplicant wireless_tools netctl dialog lvm2 --noconfirm
systemctl enable NetworkManager

# Replace this with pure shell
python3 -c "
with open('/etc/mkinitcpio.conf') as f:
    data = f.readlines()
for ix, line in enumerate(data):
    if line.startswith('HOOKS'):
        data[ix] = line.replace('block filesystems', 'block lvm2 filesystems')
        break
with open('/etc/mkinitcpio.conf', 'w') as f:
    f.writelines(data)
"

mkinitcpio -p linux
mkinitcpio -p linux-lts

python3 -c "
with open('/etc/locale.gen') as f:
    data = f.readlines()
for ix,line in enumerate(data):
    if line == '#en_US.UTF-8 UTF-8':
        data[ix] = line[1:]
with open('/etc/locale.gen', 'w') as f:
    f.writelines(data)
"

locale-gen

echo "Almost done. All that's left to do is change your root password and then create your user. Go ahead and do so now. Don't forget to add yourself to the group 'sudo' and add 'sudo' to /etc/sudoers"
echo "After you have completed the steps above, run part 3 of the install."

